import { z } from 'zod';

export const userSchema = z.object({
  username: z.string().min(3).max(50),
  email: z.string().email().optional().or(z.literal('')),
  name: z.string().max(100).optional(),
  password: z.string().min(12).optional(),
  roleName: z.string().optional(),
  status: z.enum(['active', 'inactive', 'suspended']).optional(),
});

export const pageSchema = z.object({
  title: z.string().min(1).max(200),
  slug: z.string().max(200).optional(),
  summary: z.string().max(500).optional(),
  body: z.string().optional().default(''),
  status: z.enum(['draft', 'published', 'archived']).optional(),
  seoTitle: z.string().max(70).optional(),
  seoDescription: z.string().max(160).optional(),
});

export const programSchema = z.object({
  title: z.string().min(1).max(200),
  slug: z.string().max(200).optional(),
  category: z.string().max(100).optional(),
  status: z.enum(['draft', 'published', 'archived']).optional(),
  duration: z.string().max(100).optional(),
  eligibility: z.string().optional(),
  summary: z.string().max(500).optional(),
  overview: z.string().optional(),
  authorityNote: z.string().optional(),
  admissionProcess: z.string().optional(),
  attendanceRules: z.string().optional(),
  semesterStructure: z.string().optional(),
  careerOpportunities: z.string().optional(),
  rules: z.union([z.array(z.string()), z.string()]).optional(),
  documents: z.union([z.array(z.string()), z.string()]).optional(),
  faqs: z.union([z.array(z.string()), z.string()]).optional(),
  facultyIds: z.union([z.array(z.string()), z.string()]).optional(),
  image: z.string().url().optional().or(z.literal('')),
  seoTitle: z.string().max(70).optional(),
  seoDescription: z.string().max(160).optional(),
});

export const noticeSchema = z.object({
  title: z.string().min(1).max(200),
  slug: z.string().max(200).optional(),
  category: z.string().max(100).optional(),
  date: z.string().optional(),
  expiryDate: z.string().optional(),
  status: z.enum(['active', 'expired', 'draft']).optional(),
  program: z.string().optional(),
  url: z.string().optional(),
  documentUrl: z.string().optional(),
  pinned: z.boolean().optional(),
  body: z.string().optional(),
});

export const documentSchema = z.object({
  title: z.string().min(1).max(200),
  slug: z.string().max(200).optional(),
  category: z.string().optional(),
  authority: z.string().optional(),
  documentType: z.string().optional(),
  year: z.string().optional(),
  academicYear: z.string().optional(),
  program: z.string().optional(),
  description: z.string().optional(),
  tags: z.union([z.array(z.string()), z.string()]).optional(),
  status: z.enum(['current', 'archived', 'draft', 'superseded']).optional(),
  visibility: z.enum(['public', 'internal', 'restricted']).optional(),
  file: z.string().optional(),
  fileUrl: z.string().optional(),
});

export const facultySchema = z.object({
  name: z.string().min(1).max(100),
  slug: z.string().max(200).optional(),
  photo: z.string().optional(),
  designation: z.string().optional(),
  department: z.string().optional(),
  qualification: z.string().optional(),
  experience: z.string().optional(),
  expertise: z.string().optional(),
  bio: z.string().optional(),
  publications: z.union([z.array(z.string()), z.string()]).optional(),
  contactEmail: z.string().email().optional().or(z.literal('')),
  contactPhone: z.string().optional(),
  contactVisible: z.boolean().optional(),
  spotlight: z.boolean().optional(),
  status: z.enum(['draft', 'published', 'archived']).optional(),
});

const schemas: Record<string, z.ZodType> = {
  users: userSchema,
  pages: pageSchema,
  programs: programSchema,
  notices: noticeSchema,
  documents: documentSchema,
  faculty: facultySchema,
  events: z.object({
    title: z.string().min(1).max(200),
    slug: z.string().max(200).optional(),
    category: z.string().max(100).optional(),
    summary: z.string().max(500).optional(),
    body: z.string().max(50000).optional(),
    startDate: z.string().optional(),
    endDate: z.string().optional(),
    status: z.enum(['draft', 'published', 'archived']).optional(),
    image: z.string().max(500).optional(),
    seoTitle: z.string().max(70).optional(),
    seoDescription: z.string().max(160).optional(),
  }),
  blogs: z.object({
    title: z.string().min(1).max(200),
    slug: z.string().max(200).optional(),
    summary: z.string().max(500).optional(),
    body: z.string().max(50000).optional(),
    status: z.enum(['draft', 'published', 'archived']).optional(),
    image: z.string().max(500).optional(),
    publishedAt: z.string().optional(),
    seoTitle: z.string().max(70).optional(),
    seoDescription: z.string().max(160).optional(),
  }),
  careers: z.object({
    title: z.string().min(1).max(200),
    slug: z.string().max(200).optional(),
    department: z.string().max(100).optional(),
    employmentType: z.string().max(50).optional(),
    deadline: z.string().optional(),
    status: z.enum(['draft', 'published', 'archived']).optional(),
    description: z.string().max(50000).optional(),
    eligibility: z.string().max(2000).optional(),
    noticeUrl: z.string().max(500).optional(),
    applicationUrl: z.string().max(500).optional(),
  }),
  media: z.object({
    title: z.string().min(1).max(200),
    fileName: z.string().max(255).optional(),
    url: z.string().max(500).optional(),
    mimeType: z.string().max(100).optional(),
    folder: z.string().max(100).optional(),
    altText: z.string().max(200).optional(),
    caption: z.string().max(500).optional(),
    tags: z.union([z.array(z.string()), z.string()]).optional(),
    status: z.enum(['active', 'archived']).optional(),
  }),
  forms: z.object({
    kind: z.string().max(50).optional(),
    name: z.string().max(200).optional(),
    phone: z.string().max(20).optional(),
    email: z.string().max(200).optional(),
    program: z.string().max(100).optional(),
    message: z.string().max(5000).optional(),
    status: z.enum(['new', 'contacted', 'closed', 'spam']).optional(),
    assignedTo: z.string().max(100).optional(),
    notes: z.string().max(5000).optional(),
  }),
  admissions: z.object({
    studentName: z.string().min(1).max(200),
    parentName: z.string().max(200).optional(),
    phone: z.string().min(1).max(20),
    whatsapp: z.string().max(20).optional(),
    email: z.string().max(200).optional(),
    city: z.string().max(100).optional(),
    program: z.string().max(100).optional(),
    qualification: z.string().max(200).optional(),
    message: z.string().max(5000).optional(),
    status: z.enum(['new', 'contacted', 'applied', 'enrolled', 'closed']).optional(),
    assignedTo: z.string().max(100).optional(),
    followUpAt: z.string().optional(),
    notes: z.string().max(5000).optional(),
  }),
  recruiters: z.object({
    company: z.string().min(1).max(200),
    contactPerson: z.string().max(200).optional(),
    designation: z.string().max(100).optional(),
    phone: z.string().max(20).optional(),
    email: z.string().max(200).optional(),
    hiringRequirement: z.string().max(2000).optional(),
    programInterest: z.string().max(200).optional(),
    message: z.string().max(5000).optional(),
    status: z.enum(['new', 'contacted', 'closed']).optional(),
  }),
  alumni: z.object({
    name: z.string().min(1).max(200),
    graduationYear: z.string().max(10).optional(),
    program: z.string().max(100).optional(),
    profession: z.string().max(200).optional(),
    company: z.string().max(200).optional(),
    phone: z.string().max(20).optional(),
    email: z.string().max(200).optional(),
    linkedIn: z.string().max(300).optional(),
    message: z.string().max(5000).optional(),
    status: z.enum(['new', 'verified', 'closed']).optional(),
  }),
  contacts: z.object({
    name: z.string().min(1).max(200),
    phone: z.string().max(20).optional(),
    email: z.string().max(200).optional(),
    inquiryType: z.string().max(100).optional(),
    message: z.string().max(5000).optional(),
    status: z.enum(['new', 'replied', 'closed']).optional(),
  }),
  roles: z.object({
    name: z.string().min(1).max(50),
    description: z.string().max(200).optional(),
    permissionKeys: z.union([z.array(z.string().max(50)), z.string()]).optional(),
  }),
  // Previously these three collections bypassed validation entirely. Now they
  // get a permissive but typed schema — the strictly-required fields are
  // enforced and free-form HTML body fields are bounded in length so a
  // malicious editor payload can't blow up the row.
  'site': z.object({
    name: z.string().min(1).max(200).optional(),
    shortName: z.string().max(100).optional(),
    organization: z.string().max(200).optional(),
    mission: z.string().max(5000).optional(),
    vision: z.string().max(5000).optional(),
    address: z.string().max(500).optional(),
    hours: z.string().max(200).optional(),
    phones: z.record(z.string(), z.string().max(40)).optional(),
    emails: z.record(z.string(), z.string().max(200)).optional(),
    navigation: z.array(z.tuple([z.string().max(100), z.string().max(200)])).optional(),
    values: z.array(z.string().max(200)).optional(),
    infrastructure: z.array(z.string().max(200)).optional(),
    statPlaceholders: z.array(z.string().max(200)).optional(),
  }).passthrough(),
  'homepage-sections': z.object({
    key: z.string().min(1).max(50),
    title: z.string().max(200).nullable().optional(),
    subtitle: z.string().max(500).nullable().optional(),
    body: z.string().max(50000).nullable().optional(),
    order: z.number().int().nonnegative().optional(),
    visible: z.boolean().optional(),
    status: z.enum(['draft', 'published', 'archived']).optional(),
    settings: z.record(z.string(), z.unknown()).optional(),
  }),
  'value-added-courses': z.object({
    title: z.string().min(1).max(200),
    slug: z.string().max(200).optional(),
    category: z.string().max(100).optional(),
    duration: z.string().max(100).optional(),
    eligibility: z.string().max(2000).optional(),
    summary: z.string().max(2000).optional(),
    image: z.string().max(500).optional(),
    status: z.enum(['draft', 'published', 'archived']).optional(),
  }),
};

/** Validate input data for a collection. Returns parsed data or throws. */
export function validateInput(collection: string, data: unknown): unknown {
  const schema = schemas[collection];
  if (!schema) {
    throw new Error(`No validation schema for collection: ${collection}`);
  }
  return schema.parse(data);
}
